<?php

function gf_price_request_get_current_price($node) {
  $region = gf_stock_get_current_region();
  return (int) $node->gf_region_prices[$region];
}

function gf_price_request_node_view($node, $view_mode) {
  if ($view_mode == 'full' && uc_product_is_product($node->type)) {
    $form = '';
    if (user_access('price change prequest')){
      $form = drupal_get_form('gf_price_request_change_form', $node);
    }
    $node->content['gf_price_request_form'] = $form;
  }
}

function gf_price_request_change_form($form, &$form_state, $node) {
  $form['#node'] = $node;
  $form['#attributes']['class'][] = 'gf_price_request_form';

  $form['gf_price_request_price'] = [
    '#prefix' => '<div class="current-percent"></div><span class="gf-price-request minus">◄</span>',
    '#suffix' => '<span class="gf-price-request plus">►</span>',
    '#markup' => '<span class="price-box">' . gf_price_request_get_current_price($node) . '</span>',
  ];

  $fields = ['gf_price_request_new_price', 'gf_price_request_percent'];
  foreach ($fields as $field) {
    $form[$field] = ['#type' => 'textfield', '#default_value' => ''];
    $form[$field]['#attributes']['class'][] = 'd-none';
  }

  $form['submit'] = [
    '#prefix' => '<div class="submit-button-box">',
    '#suffix' => '</div>',
    '#type' => 'submit',
    '#value' => t('Ok'),
    '#attributes' => [
      'class' => [
        'd-none',
        'new-price-submit-button'
      ],
    ],
  ];


  $path = drupal_get_path('module', 'gf_price_request');
  $form['#attached']['css'][] = $path . '/gf_price_request.css';
	$form['#attached']['js'][] = $path . '/gf_price_request.js';

  return $form;
}

function gf_price_request_change_form_submit($form, &$form_state) {
  // dsm($form);
  dsm($form_state);
}

/**
 * Implements hook_permission()
 */
function gf_price_request_permission() {
  return array(
    'price change prequest' => array(
      'title' => t('Request for price change'),
      'description' => t('Permission to make a request to change the price of the product.'),
    ),
  );
}
